### ISSUE TITLE
Add new todo on new tab page?

### ISSUE THREAD

**Issue by orschiro** [fedoranimus/today-app#15]
Hey @fedoranimus,

I am assuming [this](https://chrome.google.com/webstore/detail/today/nlaopmodobgckcknfffmkpcgfoilbeig) is your extension right?

Well, love it! The only thing I am missing is the ability to add a new todo directly on the new tab page.

What do you think? :-)

Thanks!

Robert

**Comment by fedoranimus** [comment]
Yep, that's this extension!

I would like to add the ability to create a new task on the page directly, however, I'm concerned about usability. What Todoist provides is more advanced than what I have the bandwidth for right now for creating tasks.

I'll keep this issue open and see what I can come up with as a stop-gap.

**Comment by orschiro** [comment]
> I'll keep this issue open and see what I can come up with as a stop-gap.

Thanks! That would be lovely. Your extension is the only adequate alternative to [Wunderlist new tab](https://chrome.google.com/webstore/detail/wunderlist-new-tab/fgikemaeelgbhjnhnnahcpkjpafaeion) which, however, is no longer being maintained.

**Comment by fedoranimus** [comment]
What sort of aspects of creating a new task would you like? 

I was intending to just start with the content, which would put the new task into your inbox. Is that sufficient?

**Comment by fedoranimus** [comment]
I have pushed an update out to the Chrome Web Store. Let me know what you think.

**Comment by orschiro** [comment]
Hey @fedoranimus looks great to me! Thank you so much. :-) 

Let me experiment a bit more and see if syncing with Android works well.

![image](https://user-images.githubusercontent.com/170947/38017269-dcef1464-3271-11e8-8ab0-649eca068b8f.png)
