### ISSUE TITLE
Clean input field after creating task?

### ISSUE THREAD

**Issue by orschiro** [fedoranimus/today-app#19]
Hey @fedoranimus 

Can we clean the input field after the task had been created?

I find it quite confusing that the task is being added to the list, yet the task remains visible in the input field. 

It would be cleaner and clearer to delete it after the user clicks "create".

What do you think?

**Comment by fedoranimus** [comment]
Great idea, will do.

**Comment by orschiro** [comment]
Awesome, thanks!

**Comment by fedoranimus** [comment]
Implemented and Published.

**Comment by orschiro** [comment]
Cool! Cannot wait to get the update. :-)

**Comment by orschiro** [comment]
Was able to test the new version and love it, thanks!
